##端口号
server:
  port: 8090
## mybatis配置
mybatis:
  mapper-locations: classpath*:com/springboot/traffic/dao/mapping/*.xml
  typeAliasesPackage: com.springboot.traffic.model
##日志等级
logging:
  level:
    com.springboot.traffic.dao : debug
##数据源
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/traffic?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://123.57.22.91:3306/traffic?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    db-name: traffic
    filters: log4j,wall,mergeStat
    driverClassName: com.mysql.cj.jdbc.Driver